quiz_yg.quiz_yg_type.*:
  type: config_entity
  label: 'Quiz type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    icon_uuid:
      type: string
      label: 'Icon uuid'
    description:
      type: text
      label: 'Description'
    behavior_plugins:
      type: sequence
      label: 'Plugins'
      sequence:
        type: quiz_yg.behavior.settings.[%key]
        label: 'Behavior plugins'

quiz_yg.behavior.settings_base:
  type: mapping
  label: 'Settings for base quiz_yg behavior plugin'
  mapping:
    enabled:
      type: boolean
      label: 'Enabled'

# The plugins which extend the base behavior plugin and don't provide
# any configuration form will validate on this entry.
quiz_yg.behavior.settings.*:
  type: quiz_yg.behavior.settings_base

entity_reference_selection.default:quiz_yg:
  type: entity_reference_selection.default
  mapping:
    negate:
      type: integer
    target_bundles_drag_drop:
      type: sequence
      sequence:
        type: mapping
        mapping:
          weight:
            type: integer
          enabled:
            type: boolean
    add_mode:
      type: string
    edit_mode:
      type: string
    title:
      type: string
    title_plural:
      type: string
    default_quiz_yg_type:
      type: string

field.widget.settings.entity_reference_quiz_yg:
  type: mapping
  mapping:
    title:
      type: string
    title_plural:
      type: string
    edit_mode:
      type: string
    add_mode:
      type: string
    form_display_mode:
      type: string
    default_quiz_yg_type:
      type: string

field.widget.settings.quiz_yg:
  type: mapping
  mapping:
    title:
      type: string
    title_plural:
      type: string
    edit_mode:
      type: string
    closed_mode:
      type: string
    autocollapse:
      type: string
    closed_mode_threshold:
      type: integer
    add_mode:
      type: string
    form_display_mode:
      type: string
    default_quiz_yg_type:
      type: string
    features:
      type: sequence
      sequence:
        type: string
