<?php

/**
 * @file
 * Contains webrtc.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function webrtc_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the webrtc module.
    case 'help.page.webrtc':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('WebRTC online video integration') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function webrtc_theme() {
  return [
    'webrtc' => [
      'render element' => 'children',
    ],
  ];
}
